namespace:
  name: sandbox
 
image:
  repository: techtrends 
  tag: latest
  pullPolicy: IfNotPresent

replicaCount: 1

service:
  port: 4111
  targetPort: 3111
  protocol: TCP
  type: ClusterIP

resources:
  memory: 64Mi
  CPU: 250m

limits:
  memory: 128Mi
  CPU: 500m

containerPort: 3111

livenessProbe: /healthz

readinessProbe: /healthz